package main

import (
	"flag"
	"log"
	"os"

	"snapandgo/internal/fuzzing"
)

// Exists reports whether the named file or directory exists.
func Exists(name string) bool {
	if _, err := os.Stat(name); err != nil {
		if os.IsNotExist(err) {
			return false
		}
	}
	return true
}

func main() {
	targetPtr := flag.String("t", "", "Target binary (Required)")
	breakpointPtr := flag.String("b", "", "Breakpoint file generated by the ghidra script (if empty, objdump is used)")
	flag.Parse()

	if len(*targetPtr) <= 0 {
		flag.PrintDefaults()
		os.Exit(1)
	}

	if !Exists(*targetPtr) {
		log.Fatalf("Given target file '%s' doesnt exists!", *targetPtr)
	}

	if len(*breakpointPtr) > 0 && !Exists(*breakpointPtr) {
		log.Fatalf("Given breakpoint file '%s' doesnt exists!", *breakpointPtr)
	}

	fuzzer := fuzzing.Fuzzer{
		Target:           *targetPtr,
		BreakpointSource: *breakpointPtr,
	}

	fuzzer.Fuzz()
}
